// Generated by tools/build-sw.mjs - do not edit by hand.
// Caches the whole game on first load so it runs fully offline afterwards.
const CACHE = 'dustfall-614cd964b5c8';
const FILES = [
  "./",
  "./index.html",
  "./style.css",
  "./manifest.webmanifest",
  "./src/ai.js",
  "./src/assets.js",
  "./src/audio.js",
  "./src/ballistics.js",
  "./src/config.js",
  "./src/drone.js",
  "./src/effects.js",
  "./src/game.js",
  "./src/grenades.js",
  "./src/gunmodels.js",
  "./src/hud.js",
  "./src/input.js",
  "./src/level.js",
  "./src/main.js",
  "./src/nav.js",
  "./src/physics.js",
  "./src/player.js",
  "./src/post.js",
  "./src/settings.js",
  "./src/soldier.js",
  "./src/textures.js",
  "./src/weapons.js",
  "./vendor/three/addons/loaders/GLTFLoader.js",
  "./vendor/three/addons/loaders/HDRLoader.js",
  "./vendor/three/addons/utils/BufferGeometryUtils.js",
  "./vendor/three/build/three.core.min.js",
  "./vendor/three/build/three.module.min.js",
  "./assets/models/ammo_box/ammo_box.bin",
  "./assets/models/ammo_box/ammo_box.gltf",
  "./assets/models/ammo_box/textures/ammo_box_arm_1k.jpg",
  "./assets/models/ammo_box/textures/ammo_box_diff_1k.jpg",
  "./assets/models/ammo_box/textures/ammo_box_nor_gl_1k.jpg",
  "./assets/models/barrel_03/barrel_03.bin",
  "./assets/models/barrel_03/barrel_03.gltf",
  "./assets/models/barrel_03/textures/barrel_03_arm_1k.jpg",
  "./assets/models/barrel_03/textures/barrel_03_diff_1k.jpg",
  "./assets/models/barrel_03/textures/barrel_03_nor_gl_1k.jpg",
  "./assets/models/medical_box/medical_box.bin",
  "./assets/models/medical_box/medical_box.gltf",
  "./assets/models/medical_box/textures/medical_box_arm_1k.jpg",
  "./assets/models/medical_box/textures/medical_box_diff_1k.jpg",
  "./assets/models/medical_box/textures/medical_box_nor_gl_1k.jpg",
  "./assets/models/old_tyre/old_tyre.bin",
  "./assets/models/old_tyre/old_tyre.gltf",
  "./assets/models/old_tyre/textures/old_tyre_arm_1k.jpg",
  "./assets/models/old_tyre/textures/old_tyre_diff_1k.jpg",
  "./assets/models/old_tyre/textures/old_tyre_nor_gl_1k.jpg",
  "./assets/sky/sky.jpg",
  "./assets/sky/sky_1k.hdr",
  "./assets/textures/concrete_floor_worn_001/arm.jpg",
  "./assets/textures/concrete_floor_worn_001/diff.jpg",
  "./assets/textures/concrete_floor_worn_001/nor.jpg",
  "./assets/textures/concrete_wall_008/arm.jpg",
  "./assets/textures/concrete_wall_008/diff.jpg",
  "./assets/textures/concrete_wall_008/nor.jpg",
  "./assets/textures/container_side/arm.jpg",
  "./assets/textures/container_side/diff.jpg",
  "./assets/textures/container_side/nor.jpg",
  "./assets/textures/damaged_plaster/arm.jpg",
  "./assets/textures/damaged_plaster/diff.jpg",
  "./assets/textures/damaged_plaster/nor.jpg",
  "./assets/textures/gravelly_sand/arm.jpg",
  "./assets/textures/gravelly_sand/diff.jpg",
  "./assets/textures/gravelly_sand/nor.jpg",
  "./assets/textures/green_rough_planks/arm.jpg",
  "./assets/textures/green_rough_planks/diff.jpg",
  "./assets/textures/green_rough_planks/nor.jpg",
  "./assets/textures/rusty_corrugated_iron/arm.jpg",
  "./assets/textures/rusty_corrugated_iron/diff.jpg",
  "./assets/textures/rusty_corrugated_iron/nor.jpg",
  "./icons/icon-180.png",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/icon-maskable-512.png"
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('dustfall-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  e.respondWith(
    caches.match(req, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit;
      return fetch(req).then((res) => {
        if (res.ok) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(req, copy)); }
        return res;
      }).catch(() => (req.mode === 'navigate' ? caches.match('./index.html') : Response.error()));
    }),
  );
});
