// Generates sw.js with a precache list of every file the game needs, plus a
// content hash as the cache version (so updates replace the old cache).
// Run after changing any file: `npm run build-sw`.
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';

const roots = ['index.html', 'style.css', 'manifest.webmanifest', 'src', 'vendor', 'assets', 'icons'];
const buildOnly = new Set(['src/sdf.js', 'src/sdfmodels.js', 'src/hardsurface.js', 'src/gunparts.js']); // mesh-building sources, not loaded by the game
const files = [];
const walk = (p) => {
  const st = fs.statSync(p);
  if (st.isDirectory()) for (const f of fs.readdirSync(p).sort()) walk(path.join(p, f));
  // (the Cinematic *_hq.js sculpts are only fetched by gaming PCs, then cached on first use)
  else if (!p.endsWith('LICENSE') && !path.basename(p).startsWith('.') && !/_hq\.(js|glb)$/.test(p) && !buildOnly.has(p.split(path.sep).join('/'))) files.push(p.split(path.sep).join('/'));
};
for (const r of roots) walk(r);
const hash = crypto.createHash('sha256');
for (const f of files) hash.update(f).update(fs.readFileSync(f));
const version = hash.digest('hex').slice(0, 12);

const sw = `// Generated by tools/build-sw.mjs - do not edit by hand.
// Caches the whole game on first load so it runs fully offline afterwards.
const CACHE = 'dustfall-${version}';
const FILES = ${JSON.stringify(['./', ...files.map((f) => './' + f)], null, 2)};

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('dustfall-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

// Cinematic streams full-resolution scans from Poly Haven: keep them (they never change) so the
// hundreds of megabytes download once; this cache survives game updates
const SCANS = 'tips-scans-v1';

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  if (new URL(req.url).hostname === 'dl.polyhaven.org') {
    e.respondWith(caches.open(SCANS).then((c) => c.match(req).then((hit) => hit || fetch(req).then((res) => {
      if (res.ok) c.put(req, res.clone());
      return res;
    }))));
    return;
  }
  if (new URL(req.url).origin !== location.origin) return;
  e.respondWith(
    caches.match(req, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit;
      return fetch(req).then((res) => {
        if (res.ok) { const copy = res.clone(); caches.open(CACHE).then((c) => c.put(req, copy)); }
        return res;
      }).catch(() => (req.mode === 'navigate' ? caches.match('./index.html') : Response.error()));
    }),
  );
});
`;
fs.writeFileSync('sw.js', sw);
console.log(`sw.js: ${files.length} files, cache ${version}`);
