// Builds the SDF-modelled meshes (soldier bodies, gloves, polymer gun parts)
// and stores them as a compact base64 module: src/meshdata.js.
// Run after changing src/sdfmodels.js:  node tools/build-meshes.mjs
// (or rebuild only some meshes and keep the rest: node tools/build-meshes.mjs glove gloveL)
import fs from 'fs';
import * as THREE from 'three';
import { buildAll } from '../src/sdfmodels.js';

const t0 = Date.now();
const only = process.argv.slice(2);
const meshes = await buildAll(null, only.length ? only : null);
if (only.length) {
  // keep the other meshes from the current src/meshdata.js
  const { HEADER, DATA } = await import('../src/meshdata.js');
  const bin = Buffer.from(DATA, 'base64');
  const ab = bin.buffer.slice(bin.byteOffset, bin.byteOffset + bin.length);
  const kept = {};
  for (const [name, h] of Object.entries(HEADER)) {
    if (only.includes(name)) continue;
    const g = new THREE.BufferGeometry();
    g.setAttribute('position', new THREE.BufferAttribute(new Float32Array(ab, h.pos, h.n * 3).slice(), 3));
    g.setAttribute('normal', new THREE.BufferAttribute(Float32Array.from(new Int8Array(ab, h.nor, h.n * 3), (v) => v / 127), 3));
    g.setAttribute('region', new THREE.BufferAttribute(Float32Array.from(new Uint8Array(ab, h.reg, h.n)), 1));
    g.setIndex(Array.from(h.big ? new Uint32Array(ab, h.idx, h.ni) : new Uint16Array(ab, h.idx, h.ni)));
    if (h.wrist) g.userData.wrist = h.wrist;
    kept[name] = g;
  }
  for (const name of Object.keys(HEADER)) if (!only.includes(name)) meshes[name] = kept[name];
}
const header = {};
const chunks = [];
let off = 0;
const push = (typed) => {
  const pad = (4 - (off % 4)) % 4;
  if (pad) { chunks.push(Buffer.alloc(pad)); off += pad; }
  const b = Buffer.from(typed.buffer, typed.byteOffset, typed.byteLength);
  chunks.push(b); const at = off; off += b.length; return at;
};
for (const [name, g] of Object.entries(meshes)) {
  const n = g.attributes.position.count;
  const nor = g.attributes.normal.array, q = new Int8Array(n * 3);
  for (let i = 0; i < n * 3; i++) q[i] = Math.round(Math.max(-1, Math.min(1, nor[i])) * 127);
  const reg = Uint8Array.from(g.attributes.region.array);
  const idx = n < 65536 ? Uint16Array.from(g.index.array) : Uint32Array.from(g.index.array);
  header[name] = {
    n, ni: idx.length, big: n >= 65536,
    pos: push(Float32Array.from(g.attributes.position.array)), nor: push(q), reg: push(reg), idx: push(idx),
  };
  if (g.userData.wrist) header[name].wrist = g.userData.wrist.map((v) => +v.toFixed(4));
}
const b64 = Buffer.concat(chunks).toString('base64');
fs.writeFileSync('src/meshdata.js', `// Generated by tools/build-meshes.mjs from src/sdfmodels.js. Do not edit.\nexport const HEADER = ${JSON.stringify(header)};\nexport const DATA = '${b64}';\n`);
console.log(`meshdata: ${Object.keys(header).length} meshes, ${(off / 1024).toFixed(0)} KB raw, built in ${Date.now() - t0} ms`);
